### ISSUE TITLE
problem finding tree.raxml function

### ISSUE THREAD

**Issue by raynamharris** [cromanpa94/phruta#4]
Thanks for the excellent tutorial. 

I think I don't quite have raxml properly installed in work with R. I downloaded it (version  8.2.12) using `conda install -c bioconda raxml` at the command line, but I'm getting the following error message in R. I'm using a Mac OS (10.15.7) and R version 4.1.1.

Any ideas?

```
> tree.raxml(folder='2.Alignments', 
+            FilePatterns= 'Masked', 
+            raxml_exec='raxmlHPC', 
+            Bootstrap=100, 
+            outgroup ="Mus_musculus")
Error in tree.raxml(folder = "2.Alignments", FilePatterns = "Masked",  : 
  could not find function "tree.raxml"
> system("raxmlHPC")

 Error, you must specify a model of substitution with the "-m" option
```

**Comment by cromanpa94** [comment]
My pleasure! It seems that `RAxML` is installed correctly. I can only think of two potential solutions:
1. If you're using RStudio, open it from the terminal: `open /Applications/RStudio.app`. You shouldn't have any issues when running `tree.raxml` from just `R`.
2. Based on the `could not find function "tree.raxml"` error, please make sure that the package is loaded. Maybe you were trying something else, re-started `R`/`RStudio`, and forgot to load it again?
Please do let me know if you're still having issues!

**Comment by raynamharris** [comment]
Thanks! That worked. I think I needed to open from the command line and reload the package. 

Alternatively, that could have been an error message that it was throwing when I tried to do this with my own selection of sequences and species for which there were too few to build a tree. Thanks!
